name: Swift

on: [push]

jobs:
  swiftpm-build:
    runs-on: macOS-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "12.3"
      - uses: actions/checkout@v2
      - name: Build
        run: swift build -v
  swiftpm-test:
    runs-on: macOS-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "12.3"
      - uses: actions/checkout@v2
      - name: Test
        run: swift test
  cocoapods:
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "12.3"
      - uses: actions/checkout@v2
      - name: Lint Cocoapods
        run: pod lib lint --allow-warnings
